//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34011
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventaDataModul.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDb)\\v11.0;AttachDbFilename=\"C:\\Users\\ilya\\Documents\\Visual Stud" +
            "io 2013\\Projects\\webInventa\\webInventa\\App_Data\\webInventa.mdf\";Initial Catalog=" +
            "webInventa;Integrated Security=True")]
        public string webInventaConnectionString {
            get {
                return ((string)(this["webInventaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDb)\\v11.0;AttachDbFilename=\"C:\\Users\\ilya\\Documents\\Visual Stud" +
            "io 2013\\Projects\\webInventa2\\webInventa\\App_Data\\webInventa.mdf\";Initial Catalog" +
            "=webInventa;Integrated Security=True")]
        public string webInventaConnectionString1 {
            get {
                return ((string)(this["webInventaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDb)\\v11.0;AttachDbFilename=\"D:\\Cloud@Mail.Ru\\9 семестр\\asp mvc\\" +
            "webInventa2\\webInventa\\App_Data\\webInventa.mdf\";Initial Catalog=webInventa;Integ" +
            "rated Security=True")]
        public string webInventaConnectionString2 {
            get {
                return ((string)(this["webInventaConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"D:\\Cloud@Mail.Ru\\9 семестр\\asp mvc\\" +
            "webInventa2\\webInventa\\App_Data\\webInventa.mdf\";Integrated Security=True")]
        public string webInventaConnectionString3 {
            get {
                return ((string)(this["webInventaConnectionString3"]));
            }
        }
    }
}
